default_context:
  project_name: 's2'
  project_slug: 's2'
  domain_main: 's2.com'
  domain_staging: 'stag.s2.com'
  docker_swarm_stack_name_main: 's2-com'
  docker_swarm_stack_name_staging: 'stag-s2-com'
  secret_key: 's2'
  first_superuser: 'admin@s2.com'
  first_superuser_password: 's2'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.s2.com", "https://stag.s2.com", "https://s2.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@s2.com'
  postgres_password: 's2'
  pgadmin_default_user: 'admin@s2.com'
  pgadmin_default_user_password: 's2'
  traefik_constraint_tag: 's2.com'
  traefik_constraint_tag_staging: 'stag.s2.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:s2'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
